4 Django/solutions/addressbook/addressbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
]

4 Django/solutions/addressbook/contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path("", views.index, name="index"),
    path("add_contact/", views.add_contact, name="add"),
    path("save_contact/", views.save_contact, name="save"),
    path("edit_contact/<int:contact_id>/", views.edit_contact, name="edit"),
    path("delete_contact/<int:contact_id>/", views.delete_contact, name="delete"),
    # path("api/contacts/", views.get_contacts, name="get_contacts")
]

4 Django/solutions/addressbook/contacts/models.py
from django.db import models

# Create your models here.
class AddressContact(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=40)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=30)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.first_name + " " + self.last_name

4 Django/solutions/addressbook/contacts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import AddressContact

# Create your views here.
def index(request):

    addresses = AddressContact.objects.order_by('-last_name')
    context = {
        'contacts': addresses
    }

    # return HttpResponse('Hello World!')
    return render(request, 'contacts/index.html', context)

def add_contact(request):  
    # return HttpResponse('Add contact')
    return render(request, 'contacts/add_contact.html')

def save_contact(request):
    print(request.POST)
    contacts = request.POST

    output = AddressContact(
        first_name=contacts['first-name'],
        last_name=contacts['last-name'],
        email=contacts['email'],
        phone_number=contacts['phone-number'],
        address=contacts['address']
    )
    output.save()
    return HttpResponseRedirect(reverse('contacts:index'))

def edit_contact(request, contact_id):
    contact = get_object_or_404(AddressContact, pk=contact_id)

    if request.method == 'GET':

        # return HttpResponse(f'Id: {contact_id}')
        return render(request, 'contacts/edit_contact.html', {'contact': contact})
    elif request.method == "POST":
        contact.first_name = request.POST['first-name']
        contact.last_name = request.POST['last-name']
        contact.email = request.POST['email']
        contact.phone_number = request.POST['phone-number']
        contact.address = request.POST['address']

        contact.save()
        return HttpResponseRedirect(reverse('contacts:index'))


def delete_contact(request, contact_id):
    contact = get_object_or_404(AddressContact, pk=contact_id)

    contact.delete()

    return HttpResponseRedirect(reverse('contacts:index'))

4 Django/solutions/addressbook/contacts/templates/contacts/add_contact.html
{% extends 'contacts/base.html' %}

{% block title %}
Add Contact
{% endblock %}


{% block style %}
<style>
    form{
        display: grid;
        grid-template-columns: auto 1fr;
        gap: 1rem;
    }
</style>
{% endblock %}

{% block content %}
    <form id="contact-fields" class="container" action="{% url 'contacts:save' %}" method="POST">
        {% csrf_token %}
        <label for="first-name">First Name</label>
        <input for="contact-fields" name="first-name" placeholder="First Name" type="text">
        <label for="last-name">Last Name</label>
        <input for="contact-fields" name="last-name" placeholder="Last Name" type="text">
        <label for="email">Email</label>
        <input for="contact-fields" name="email" placeholder="Email" type="text">
        <label for="phone-number">Phone Number</label>
        <input for="contact-fields" name="phone-number" placeholder="Phone Number" type="text">
        <label for="address">Address</label>
        <input for="contact-fields" name="address" placeholder="Address" type="text">
        <input class="btn btn-primary" type="submit" value="Save Contact">
    </form>
{% endblock %}

4 Django/solutions/addressbook/contacts/templates/contacts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block style %}{% endblock %}
</head>
<body>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  
</body>
</html>

4 Django/solutions/addressbook/contacts/templates/contacts/edit_contact.html
{% extends 'contacts/base.html' %}

{% block title %}
Edit Contact
{% endblock %}


{% block style %}
<style>
    form{
        display: grid;
        grid-template-columns: auto 1fr;
        gap: 1rem;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <form id="contact-fields" action="{% url 'contacts:edit' contact.id %}" method="POST">
        {% csrf_token %}
        <label for="first-name">First Name</label>
        <input value="{{contact.first_name}}" for="contact-fields" name="first-name" placeholder="First Name" type="text">
        <label for="last-name">Last Name</label>
        <input value="{{contact.last_name}}" for="contact-fields" name="last-name" placeholder="Last Name" type="text">
        <label for="email">Email</label>
        <input value="{{contact.email}}" for="contact-fields" name="email" placeholder="Email" type="text">
        <label for="phone-number">Phone Number</label>
        <input value="{{contact.phone_number}}" for="contact-fields" name="phone-number" placeholder="Phone Number" type="text">
        <label for="address">Address</label>
        <input value="{{contact.address}}" for="contact-fields" name="address" placeholder="Address" type="text">
        <input class="btn btn-primary" type="submit" value="Update Contact">
    </form>
    <a class="btn btn-danger" href="{% url 'contacts:delete' contact.id %}">Delete Me</a>
</div>
{% endblock %}

4 Django/solutions/addressbook/contacts/templates/contacts/index.html
{% extends 'contacts/base.html' %}

{% block title %}
Home Page
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}
    <a href="{% url 'contacts:add' %}">Add Contact</a>
    {% if contacts %}
        {% for contact in contacts %}
        
        
        <div class="accordion" id="accordionExample">
            <div class="card">
              <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                  <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse{{contact.id}}" aria-expanded="false" aria-controls="collapseOne">
                    {{contact.first_name}} {{contact.last_name}}
                  </button>
                </h2>
              </div>
          
              <div id="collapse{{contact.id}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                    <ul>
                        <li>{{contact.address}}</li>
                        <li>{{contact.phone_number}}</li>
                        <li>{{contact.email}}</li>
                    </ul>
                    <a href="{% url 'contacts:edit' contact.id %}"><h4>Edit Contact</h4></a>
                </div>
              </div>
            </div>            
          </div>
        {% endfor %}
    {% else %}
        <h1>No contacts found.</h1>
    {% endif %}
{% endblock %}

4 Django/solutions/addressbook/contacts/templates/contacts/index.vue.html
{% extends 'contacts/base.html' %}

{% block title %}
Home Page
{% endblock %}

{% block style %}
<style>

</style>
{% endblock %}

{% block content %}


<div id="app">
    <ul v-for="contact in contacts">
        <li>[[contact.first_name]]</li>
    </ul>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js" integrity="sha512-quHCp3WbBNkwLfYUMd+KwBAgpVukJu5MncuQaWXgCrfgcxCJAq/fo+oqrRKOj+UKEmyMCG3tb8RB63W+EmrOBg==" crossorigin="anonymous"></script>
<script>
    var app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#app',
      data: {
          message: 'Hello Vue!',
          contacts: '',
      },
      methods: {
      },
      created: function() {
        axios.get('http://localhost:8000/api/contacts/')
        .then(response => {
            this.contacts = response.data
        })
        // this.contacts = JSON.parse(data)
      }
    });
</script>
{% endblock %}