4 Django/solutions/contactsproj2/contactsapp/urls.py
from django.urls import path
from . import views

app_name = 'contactsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('home/', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('edit/<int:contact_id>/', views.edit, name='edit'),
]

4 Django/solutions/contactsproj2/contactsproj2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contactsapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4 Django/solutions/contactsproj2/contactsapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contacts')
    image = models.ImageField(upload_to='profile_images/', null=True)

    def name(self):
        return self.first_name + ' ' + self.last_name
    
    def __str__(self):
        return self.name()

4 Django/solutions/contactsproj2/contactsapp/forms.py
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        # fields = '__all__'
        exclude = ['user']

4 Django/solutions/contactsproj2/contactsapp/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import ContactForm
from .models import Contact
import requests

from django.conf import settings


# from django.contrib.auth import login as login_user
import django.contrib.auth

def index(request):
    return render(request, 'contactsapp/index.html')

def register(request):

    if request.method == 'POST': # receiving form submission

        # recaptcha
        recaptcha_data = {
            'response': request.POST['g-recaptcha-response'],
            'secret': settings.RECAPTCHA_SECRET_KEY
        }
        response = requests.post('https://www.google.com/recaptcha/api/siteverify', data=recaptcha_data)

        if (response.json()['success'] == False):
            message = 'invalid_recaptcha'
            return render(request, 'contactsapp/register.html', {'message': message})
        
        # get data out of form submission
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        retype_password = request.POST['retype_password']

        if password != retype_password:
            message = 'passwords_dont_match'
            return render(request, 'contactsapp/register.html', {'message': message})

        # if a user doesn't exist with that username
        if User.objects.filter(username=username).exists():
            message = 'user_already_exists'
            return render(request, 'contactsapp/register.html', {'message': message})

             
        # create the user
        user = User.objects.create_user(username, email, password)
        # log the user in (sets a cookie)
        django.contrib.auth.login(request, user)
        # redirect to the home page
        return HttpResponseRedirect(reverse('contactsapp:home'))
            
    return render(request, 'contactsapp/register.html', {'recaptcha_public_key': settings.RECAPTCHA_PUBLIC_KEY})


def login(request):
    message = ''
    if request.method == 'POST':
        print(request.GET)
        username = request.POST['username']
        password = request.POST['password']
        user = django.contrib.auth.authenticate(request, username=username, password=password)
        if user is None:
            message = 'not_found'
        else:
            # log the user in (sets a cookie)
            django.contrib.auth.login(request, user)
            next = request.GET.get('next', reverse('contactsapp:home'))
            # redirect to the next page
            return HttpResponseRedirect(next)
    return render(request, 'contactsapp/login.html', {'message': message})

def logout(request):
    django.contrib.auth.logout(request)
    return HttpResponseRedirect(reverse('contactsapp:login'))

@login_required
def home(request):
    # contacts = Contact.objects.filter(user=request.user)
    # contacts = Contact.objects.filter(user_id=request.user.id)
    contacts = request.user.contacts.all()
    context = {
        'contacts': contacts
    }
    return render(request, 'contactsapp/home.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            print(form.instance)

            # form.save()
            # return HttpResponseRedirect(reverse('contactsapp:home'))

            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return HttpResponseRedirect(reverse('contactsapp:home'))
    else:
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'contactsapp/create.html', context)

@login_required
def edit(request, contact_id):
    # contact = request.user.contacts.get(id=contact_id)
    # contact = get_object_or_404(request.user.contacts, id=contact_id)
    contact = get_object_or_404(Contact, id=contact_id, user=request.user)
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('contactsapp:home'))
    else:
        form = ContactForm(instance=contact)
    context = {
        'form': form
    }
    return render(request, 'contactsapp/edit.html', context)

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </body>
    <style>
        body {
            margin: 0;
        }
        nav {
            padding:20px;
            background-color:blue;
            color:white;
            display:flex;
            flex-direction:row;
            justify-content:space-between;
            align-items:center;
        }
        #title {
            font-size:40px;
        }
        main {
            max-width:800px;
            margin: 0 auto;
        }
        a {
            color:orange;
        }
        a:visited {
            color:darkorange;
        }
    </style>
</head>
<body>
    <main>
        <nav>
            <span id="title">Contacts</span>
            <div>
                {% if user.is_authenticated %}
                <span>Logged in as {{user.username}}</span>
                <a href="{% url 'contactsapp:logout' %}">logout</a>
                {% else %}
                <a href="{% url 'contactsapp:login' %}">login</a>
                <span>|</span>
                <a href="{% url 'contactsapp:register' %}">register</a>
                {% endif %}
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/create.html
{% extends 'contactsapp/base.html' %}

{% load bootstrap %}

{% block content %}
<h1>Create Contact</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button class="btn btn-primary" type="submit">Create Contact</button>
</form>
{% endblock %}

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/edit.html
{% extends 'contactsapp/base.html' %}

{% load bootstrap %}


{% block content %}
<h1>Edit Contact</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save Contact</button>
    </div>
</form>
{% endblock %}

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/home.html
{% extends 'contactsapp/base.html' %}


{% block content %}
<style>
    table img {
        width:100px;
    }
</style>
<h1>{{user.username | title}}'s Contacts</h1>
<a href="{% url 'contactsapp:create' %}">Create New Contact</a>
<table>
    {% for contact in contacts %}
    <tr>
        <td><img src="{{contact.image.url}}"/></td>
        <td>{{contact.name}}</td>
        <td><a href="{% url 'contactsapp:edit' contact.id %}">edit</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/index.html
{% extends 'contactsapp/base.html' %}


{% block content %}
<h1>Contacts App</h1>
<div><a href="{% url 'contactsapp:login' %}">Login</a> or <a href="{% url 'contactsapp:register' %}">register</a> to start entering contacts!</div>
{% endblock %}

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/login.html
{% extends 'contactsapp/base.html' %}


{% block content %}
    {% if message == 'not_found' %}
    <div style="color:red">No user was found with that username and password</div>
    {% endif %}
    <h1>Login</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username"/>
        <input type="password" name="password" placeholder="password"/>
        <button type="submit">login</button>
    </form>
    <div><a href="{% url 'contactsapp:register' %}">register</a></div>
{% endblock %}

4 Django/solutions/contactsproj2/contactsapp/templates/contactsapp/register.html
{% extends 'contactsapp/base.html' %}


{% block content %}

{% if message %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {% if message == 'passwords_dont_match' %}
    The passwords entered do not match!
    {% elif message == 'user_already_exists' %}
    A user with that username already exists
    {% elif message == 'invalid_recaptcha' %}
    Invalid recaptcha!
    {% endif %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<h1>Register</h1>
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username" required />
    <input type="email" id="input_email" name="email" placeholder="email" required />
    <input type="password" id="input_password" name="password" placeholder="password" required />
    <input type="password" id="input_retype_password" name="retype_password" placeholder="retype password" required />
    <div class="g-recaptcha" data-sitekey="{{recapatcha_public_key}}"></div>
    <button id="btn_register" type="submit">Register</button>
</form>
<div><a href="{% url 'contactsapp:login' %}">login</a></div>

<script>
    let input_email = document.querySelector('#input_email')
    let input_password = document.querySelector('#input_password')
    let input_retype_password = document.querySelector('#input_retype_password')
    let btn_register = document.querySelector('#btn_register')
    btn_register.addEventListener('click', function (event) {
        if (!input_email.value.match(/^.+@.+\..+$/)) {
            event.preventDefault() // prevent the form from being submitted
            alert('That email address is in a bad format')
        }
        if (input_password.value != input_retype_password.value) {
            event.preventDefault() // prevent the form from being submitted
            alert('The passwords don\'t match! :(')
        }
    })

</script>
{% endblock %}