4 Django/solutions/todospaproj/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('todos/', views.todos, name='todos'),
    path('priorities/', views.priorities, name='priorities'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('complete_todo/', views.complete_todo, name='complete_todo'),
    path('delete_todo/', views.delete_todo, name='delete_todo'),
    path('clear_completed/', views.clear_completed, name='clear_completed'),
    path('save_edited_todo/', views.save_edited_todo, name='save_edited_todo'),
]

4 Django/solutions/todospaproj/main/models.py
from django.db import models


class Priority(models.Model):
    name = models.CharField(max_length=200)
    order = models.IntegerField()

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['order']


class TodoItem(models.Model):
    text = models.CharField(max_length=200)
    priority = models.ForeignKey(Priority, on_delete=models.PROTECT, related_name='todo_items')
    date_created = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.priority.name + ' ' + self.text

4 Django/solutions/todospaproj/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import json
from django.utils import timezone

from .models import TodoItem, Priority


def index(request):
    return render(request, 'main/index.html')


def add_todo(request):
    data = json.loads(request.body)
    
    # priority = Priority.objects.get(id=data['priority_id'])
    # todo_item = TodoItem(..., priority=priority)

    todo_item = TodoItem(text=data['todo_text'], priority_id=data['priority_id'])
    todo_item.save()

    return HttpResponse('ok')


def complete_todo(request):
    todo_item_id = request.GET['todo_item_id']
    todo_item = TodoItem.objects.get(id=todo_item_id)
    todo_item.date_completed = timezone.now()
    todo_item.save()
    return HttpResponse('ok')

def delete_todo(request):
    todo_item_id = request.GET['todo_item_id']
    todo_item = TodoItem.objects.get(id=todo_item_id)
    todo_item.delete()
    return HttpResponse('ok')


def todos(request):
    todos = TodoItem.objects.order_by('date_completed', '-priority', 'date_created')
    todo_data = []
    for todo in todos:
        todo_data.append({
            'id': todo.id,
            'text': todo.text,
            'priority': {
                'id': todo.priority.id,
                'name': todo.priority.name,
                'order': todo.priority.order
            },
            'date_created': todo.date_created.strftime('%Y-%m-%d %H:%M'),
            'date_completed': todo.date_completed.strftime('%Y-%m-%d %H:%M') if todo.date_completed else None,
        })
    return JsonResponse({'todos': todo_data})


def priorities(request):
    data = {'priorities': []}
    priorities = Priority.objects.all()
    for priority in priorities:
        data['priorities'].append({
            'id': priority.id,
            'name': priority.name,
            'order': priority.order,
        })
    return JsonResponse(data)


def clear_completed(request):
    completed_todos = TodoItem.objects.filter(date_completed__isnull=False)
    completed_todos.delete()

    return HttpResponse('ok')

def save_edited_todo(request):
    todo_data = json.loads(request.body)

    todo_item = TodoItem.objects.get(id=todo_data['id'])
    todo_item.text = todo_data['text']
    
    # priority = Priority.objects.get(id=todo_data['priority']['id'])
    # todo_item.priority = priority

    todo_item.priority_id = todo_data['priority']['id']
    todo_item.save()

    return HttpResponse('ok')

4 Django/solutions/todospaproj/main/templates/main/index-table.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"
        integrity="sha512-quHCp3WbBNkwLfYUMd+KwBAgpVukJu5MncuQaWXgCrfgcxCJAq/fo+oqrRKOj+UKEmyMCG3tb8RB63W+EmrOBg=="
        crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <style>
        .low {
            color:blue;
        }
        .medium {
            color:orange;
        }
        .high {
            color: red;
        }
        .completed {
            color:grey;
            text-decoration: line-through;
        }
        .input_row {
            margin-bottom:20px;
            justify-content:space-evenly;
        }
        .col-8 {
            padding-left: 0 !important;
        }
        .col-2 {
            padding-right: 0 !important;
        }
        
    </style>
</head>
<body>
    <div id="app" class="container">
        <div class="row">
            <h1>Todo List</h1>
        </div>
        <div class="row input_row">
            <div class="col-8">
                <input type="text" class="form-control" placeholder="Enter a Todo" v-model="input_todo_text"/>
            </div>
            <div class="col-2">
                <select class="form-control" v-model="input_priority_id">
                    <option value="" disabled>Select a Priority</option>
                    <option v-for="priority in priorities" v-bind:value="priority.id">[[priority.name]]</option>
                </select>
            </div>
            <div class="col-2">
                <a class="btn btn-primary" v-on:click="addTodo">Add Todo</a>
            </div>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Todo</th>
                        <th scope="col">Priority</th>
                        <th scope="col">Created</th>
                        <th scope="col">Completed</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="todo in todos" v-bind:class="{completed: todo.date_completed}">
                        <td>[[ todo.text ]]</td>
                        <td v-bind:class="!todo.date_completed? todo.priority: ''">[[ todo.priority | capitalize ]]</td>
                        <td>[[ todo.date_created ]]</td>
                        <td>[[ todo.date_completed ]]</td>
                        <td>
                            <a v-if="!todo.date_completed" class="btn btn-success" v-on:click="completeTodo(todo.id)">complete</a>
                            <a v-else class="btn btn-danger" v-on:click="deleteTodo(todo.id)">delete</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <script>
        let app = new Vue({
            el: '#app',
            delimiters: ['[[', ']]'],
            data: {
                input_todo_text: '',
                input_priority_id: '',
                todos: [],
                priorities: []
            },
            methods: {
                addTodo: function() {
                    axios({
                        url: '{% url "main:add_todo" %}',
                        method: 'post',
                        data: {
                            todo_text: this.input_todo_text,
                            priority_id: this.input_priority_id
                        },
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}'
                        }
                    }).then(response => {
                        console.log(response.data)
                        // this.todos.append({
                        //     text: this.input_todo_text,
                        //     priority: ''
                        // })
                        this.getTodos()
                    })
                },
                getTodos: function() {
                    axios({
                        url: '{% url "main:todos" %}',
                        method: 'get'
                    }).then(response => {
                        // console.log(response.data)
                        this.todos = response.data.todos
                    })
                },
                completeTodo: function(todo_item_id) {
                    axios({
                        url: '{% url "main:complete_todo" %}',
                        method: 'get',
                        params: {
                            todo_item_id: todo_item_id
                        }
                    }).then(response => {
                        console.log(response.data)
                        this.getTodos()
                    })
                },
                deleteTodo: function(todo_item_id) {
                    axios({
                        url: '{% url "main:delete_todo" %}',
                        method: 'get',
                        params: {
                            todo_item_id: todo_item_id
                        }
                    }).then(response => {
                        console.log(response.data)
                        this.getTodos()
                    })
                },
            },
            filters: {
                capitalize: function (value) {
                    if (!value) return ''
                    value = value.toString()
                    return value.charAt(0).toUpperCase() + value.slice(1)
                }
            },
            created: function () {
                this.getTodos()
                axios({
                    url: '{% url "main:priorities" %}',
                    method: 'get'
                }).then(response => {
                    this.priorities = response.data.priorities
                })
            }
        })
    </script>
</body>

</html>

4 Django/solutions/todospaproj/main/templates/main/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <style>
        .flip-list-move {
            transition: transform 1s;
        }
    </style>
</head>

<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.14.1/lodash.min.js"></script>

    <div id="flip-list-demo" class="demo">
        <button v-on:click="shuffle">Shuffle</button>
        <table>
            <transition-group name="flip-list" tag="tbody">
                <tr v-for="item in items" v-bind:key="item">
                    <td>{{ item }}</td>
                </tr>
            </transition-group>
        </table>
    </div>
    <script>
        new Vue({
            el: '#flip-list-demo',
            data: {
                items: [1, 2, 3, 4, 5, 6, 7, 8, 9]
            },
            methods: {
                shuffle: function () {
                    this.items = _.shuffle(this.items)
                }
            }
        })
    </script>
</body>

</html>